### ISSUE TITLE
Log settings being ignore when packaged

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1758]
Seems like version 1.3.2 has a regression related with log configuration.

To reproduce this:
- take the java-protobuf-customer-registry-quickstart
- mvn install
- adjust the docker-compose.yml to  include the image produce previously:
```yml
  customer-registry:
    image: my-docker-repo/customer-registry:1.0-SNAPSHOT-20230806115623
    ports:
      - '8080:8080'
    environment:
      HOST: 0.0.0.0
```
- run
- logs will show a lot of these even when not in DEBUG: `09:15:10.319 [kalix-akka.actor.default-dispatcher-4] DEBUG akka.http.impl.engine.http2.Http2ServerDemux - Changing state from WaitingForNetworkToSendData to WaitingForNetworkToSendControlFrames`

See report from forum[here](https://discuss.kalix.io/t/what-happened-to-the-logging-configuration/272/4).
