### ISSUE TITLE
Make it easier to change runtime and service ports

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1997]
When running multi-services tests, users need to add a few changes to the docker-compose file.

* they need to add a env var for the runtime: `HTTP_PORT:9001` (that's runtime internal port)
* they need to change the port mapping to "9001:9001"
* they need to pick another port for the service USER_SERVICE_PORT:8081

The first two changes are not so obvious for the users. Someone experienced with Docker will think about only changing the exposed port "9001:9000", but then the user service running on host machine will try to talk to the runtime through port 9000 and it won't work. 

A possible solution (but also not perfect) is to use a `.env` file. 
Docker Compose reads this file when it starts and do variable substitution. 

The env file would look like this:

```
=❯ cat .env 
HTTP_PORT=9000
USER_SERVICE_PORT=8080
```

The compose file would look like this:

```
version: "3"
services:
  kalix-runtime:
    image: gcr.io/kalix-public/kalix-runtime:1.1.29
    container_name: java-spring-fibonacci-action
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
      HTTP_PORT: ${HTTP_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
```

Then, the runtime http port will be defined in a single place, as well as the USER_SERVICE_PORT. 
And we can document that `.env` is the file to edit whenever you want to have more than one service running on your local machine.

I don't find it an ideal solution, but if our samples and templates adopt this format, we can easily explain how to change the port number and then, if the user keep the original compose file, the mapping will be correct.

**Comment by octonato** [comment]
Additionally, we can validate the ports inside the mvn/sbt plugin. If the final docker config says: 9001:9000 for example, then we know that this services will be broken and we can help the user in finding the issue.

**Comment by octonato** [comment]
For reference:
https://docs.docker.com/compose/environment-variables/set-environment-variables/#compose-file

**Comment by aludwiko** [comment]
Interesting, we can potentially use this .env file for other purposes, when it comes to the docker-compose I’m ok with the idea, I would just put a comment in the docker-compose file explaining where to look for values.

**Comment by octonato** [comment]
I have a call with @hedefalk today to brainstorm once more about it. 

We settle for an explicit advertised port, but will will add the .env to the docker-compose. 

At the end, the file will look like:

```
version: "3"
services:
  kalix-runtime:
    image: gcr.io/kalix-public/kalix-runtime:1.1.29
    container_name: java-spring-fibonacci-action
    ports:
      - "${ADVERTISED_HTTP_PORT}:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
      ADVERTISED_HTTP_PORT: ${ADVERTISED_HTTP_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
```

With enough comments to clarify it to users. 

We won't be forced to change the internal runtime port.
