### ISSUE TITLE
Scala SDK can't connect to Kafka locally

### ISSUE THREAD

**Issue by Marius-Stroe** [lightbend/kalix-jvm-sdk#2289]
I've been trying to use Kafka locally, as in [java-protobuf-customer-registry-kafka-quickstart](https://github.com/lightbend/kalix-jvm-sdk/tree/main/samples/java-protobuf-customer-registry-kafka-quickstart), but with the Scala SDK. However, it keeps failing. I'm attaching the `docker-compose.yml` file and the console errors.

Any thoughts on what might be wrong? Are you sure kafka can still be run locally?

PS: Since discuss.kalix.io is gone, I'm posting this here. Is there a better place to ask such questions?

```yaml
services:
  kalix-runtime:
    image: gcr.io/kalix-public/kalix-runtime:1.2.7
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "${ADVERTISED_HTTP_PORT}:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dkalix.proxy.eventing.support=kafka
        -Dkalix.proxy.eventing.kafka.bootstrap-servers=kafka:19092

      ADVERTISED_HTTP_PORT: ${ADVERTISED_HTTP_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      ACL_ENABLED: "false"

  kafka:
    image: confluentinc/cp-kafka:7.2.6
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10

  zookeeper:
    image: zookeeper:3.9
    ports:
      - 2181:2181
```

```
...
[info] INFO  kalix.javasdk.impl.DiscoveryImpl - Info reported from Kalix system:  Kafka broker set up: bootstrap-servers: PLAINTEXT://kafka:19092, authentication: none, transport: plaintext
...
[info] ERROR kalix.javasdk.impl.DiscoveryImpl - Error reported from Kalix system: KLX-00418 Failed to list topics on the Kafka broker, trying to check if topic [some-topic] exists
[info] Please verify that the Kafka broker config file is correct
[info] See documentation: https://docs.kalix.io/java-protobuf/publishing-subscribing.html
```
